package pe.edu.upc.ice.track.platform.monitoring.infrastructure.persistence.jpa.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA persistence entity for {@code SensorReading}.
 *
 * <p>No persistence annotation ever appears on the domain aggregate; this class, and
 * {@code SensorReadingPersistenceAssembler}, are the only places that know about the
 * relational schema.</p>
 */
@Entity
@Table(name = "sensor_readings")
@Getter
@Setter
@NoArgsConstructor
public class SensorReadingPersistenceEntity {

  /**
   * Primary key of the entity, auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Unique identifier for the sensor reading, generated by the client to prevent duplicates on retries.
   */
  @Column(nullable = false, unique = true)
  private UUID readingUid;

  /**
   * Identifier of the equipment that generated this reading, used to associate readings with specific assets.
   */
  @Column(nullable = false)
  private Long equipmentId;

  /**
   * Identifier of the device that generated this reading, used to associate readings with specific devices.
   */
  @Column(nullable = false)
  private Long deviceId;

  /**
   * Minimum temperature observed in the reading window, in Celsius.
   */
  private Double minTemperature;
  /**
   * Maximum temperature observed in the reading window, in Celsius.
   */
  private Double maxTemperature;
  /**
   * Average temperature observed in the reading window, in Celsius.
   */
  private Double avgTemperature;
  /**
   * Average relative humidity observed in the reading window, as a percentage.
   */
  private Double humidity;
  /**
   * Number of raw samples that were aggregated into this reading.
   */
  private Integer sampleCount;

  /**
   * Timestamp assigned by the device clock when the reading was recorded, used to track when the data was collected.
   */
  @Column(nullable = false)
  private LocalDateTime recordedAt;

  /**
   *  Timestamp when the reading was received by the platform, used to track when the data was ingested.
   */
  @Column(nullable = false)
  private LocalDateTime receivedAt;
}
